const fs = require('fs');
const path = require('path');

async function main() {
    // 假设我们要导出 Sepolia 网络的部署信息
    const network = "sepolia"; 
    const deploymentDir = path.join(__dirname, `../deployments/${network}`);

    if (!fs.existsSync(deploymentDir)) {
        console.log(`No deployments found for ${network}`);
        return;
    }

    // 读取 MyToken 的部署信息
    const myTokenData = JSON.parse(fs.readFileSync(path.join(deploymentDir, "MyToken.json")));
    const poolLockData = JSON.parse(fs.readFileSync(path.join(deploymentDir, "NFTPoolLockAndRelease.json")));

    const configContent = `
# Auto-generated by Hardhat
contract.mytoken.address=${myTokenData.address}
contract.pool.lock.address=${poolLockData.address}
chain.id=${myTokenData.chainId || 11155111}
    `;

    // 输出路径：指向 backend 模块的 resources 目录
    const javaResourcesPath = path.join(__dirname, "../backend/src/main/resources/contracts.properties");
    
    fs.writeFileSync(javaResourcesPath, configContent);
    console.log("Config generated at:", javaResourcesPath);
    console.log(configContent);
}

main();